language: ruby
install: bundle install --local
cache:
  apt: true
  bundler: true
  directories:
  - vendor/cache

rvm:
- 2.3.1

addons:
  addons:
  postgresql: 9.3
  apt:
    packages:
    - postgresql-9.3-postgis-2.3
  code_climate:
      repo_token: 3045bb415f20a2b7f8715ab52458747dddc35b71848a631553a391fb38ecbc2b

before_script:
  - psql -U postgres -c "create extension postgis"
  - ./scripts/travis
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 1

script:
- RAILS_ENV=test bundle exec rspec --pattern 'c*/*_spec.rb,h*/*_spec.rb'

env:
  matrix:
  - DATABASE_URL="postgres://localhost/evercam_tst"
  global:
  - secure: eDG0eEdm2HjiEKA4WZukbYvTn3kYlM+0SsZmOU0yE/6qV8tNO9erqaI0Wyz0E3i5Lhis2wKLucF4GVl8/QLxXYVTqRfW13YfLtIBoqMrUVKZaM9Lw2DRbwRb/CcKcCeuaV2dCkaB0WGvlcybNX8DXVdzP7MXSdWVJ8oW4UFzscI=
  - secure: bHbxbeB5q+q+cCXDzHzx33W4vfkte/ihcKjlKUn+ukHyBcrcMeZkvc3EpxznqAmiPC6sWV+NvMQ7JyAUbdI1L6I5Mw26UOmPMzeDDdK3EhoTtKItRKxHOCrVa7uv+ShWgGdLWeStQwrROv+95oruQ2VNsge0DRjQ5Ge1+YbY8Rg=

branches:
  only: master

dist: precise
